import { resolve } from "node:path";
import { defineConfig } from "vite";

export default defineConfig({
  build: {
    rollupOptions: {
      input: {
        main: resolve(__dirname, "index.html"),
        demo: resolve(__dirname, "demo/index.html"),
        newYorkHeating: resolve(__dirname, "demo/new-york-heating/index.html"),
        iceAgeMechanical: resolve(__dirname, "demo/ice-age-mechanical/index.html"),
        coilTechs: resolve(__dirname, "demo/coil-techs/index.html"),
        tonnageHvac: resolve(__dirname, "demo/tonnage-hvac/index.html"),
        airWaveAc: resolve(__dirname, "demo/air-wave-ac/index.html"),
        dierksHeating: resolve(__dirname, "demo/dierks-heating/index.html"),
        slHvacSystems: resolve(__dirname, "demo/sl-hvac-systems/index.html"),
        vegaHvac: resolve(__dirname, "demo/vega-hvac/index.html"),
        geminiThermoHvac: resolve(__dirname, "demo/gemini-thermo-hvac/index.html"),
        brownstoneHeatingAc: resolve(__dirname, "demo/brownstone-heating-ac/index.html"),
        ptHeatingAirConditioning: resolve(__dirname, "demo/pt-heating-air-conditioning/index.html"),
        allHvac: resolve(__dirname, "demo/all-hvac/index.html"),
        systematicHeatingCooling: resolve(__dirname, "demo/systematic-heating-cooling/index.html"),
        northPoleCooling: resolve(__dirname, "demo/north-pole-cooling/index.html"),
        pandaHvac: resolve(__dirname, "demo/panda-hvac/index.html"),
        forgenieHvac: resolve(__dirname, "demo/forgenie-hvac/index.html"),
        coolTechHvac: resolve(__dirname, "demo/cool-tech-hvac/index.html"),
        eliteAcBeyond: resolve(__dirname, "demo/elite-ac-beyond/index.html"),
        brooklynAirSolutions: resolve(__dirname, "demo/brooklyn-air-solutions/index.html"),
        macAirHvac: resolve(__dirname, "demo/mac-air-hvac/index.html"),
        atlantidaHvac: resolve(__dirname, "demo/atlantida-hvac/index.html"),
        scPrimeEnergy: resolve(__dirname, "demo/sc-prime-energy/index.html"),
        bobMims: resolve(__dirname, "demo/bob-mims/index.html"),
        scaran: resolve(__dirname, "demo/scaran/index.html"),
        vincoMechanical: resolve(__dirname, "demo/vinco-mechanical/index.html"),
        twoTwelveHvac: resolve(__dirname, "demo/212-hvac/index.html"),
        mrAirNyc: resolve(__dirname, "demo/mr-air-nyc/index.html"),
        freshCoolAir: resolve(__dirname, "demo/fresh-cool-air/index.html"),
        nuWayHvac: resolve(__dirname, "demo/nu-way-hvac/index.html"),
        climateControlHvac: resolve(__dirname, "demo/climate-control-hvac/index.html"),
        airRescueNy: resolve(__dirname, "demo/air-rescue-ny/index.html"),
        profairCorp: resolve(__dirname, "demo/profair-corp/index.html"),
        lebessMechanical: resolve(__dirname, "demo/lebess-mechanical/index.html"),
        aquatechMechanical: resolve(__dirname, "demo/aquatech-mechanical/index.html"),
        temperatureManagement: resolve(__dirname, "demo/temperature-management/index.html"),
        ramsMechanical: resolve(__dirname, "demo/rams-mechanical/index.html"),
      },
    },
  },
});
